# Copyright (c) 2024 Arjuna Technologies, Newcastle upon Tyne. All rights reserved.

version: 2.1

jobs:
  dsbase:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          docker_layout_caching: true
      - run: |
          echo "Building"
          echo "  Repo Name: " $CIRCLE_PROJECT_REPONAME
          echo "  Branch:    " $CIRCLE_BRANCH
          echo "  Tag:       " $CIRCLE_TAG
      - run:
          command: |
              sudo apt-get update -y
              sudo apt-get install -y r-base-core cmake
      - run:
          command: |
              sudo apt-get install -y libxml2-dev libuv1-dev
      - run:
          command: |
              echo "options(Ncpus=4)" >> ~/.Rprofile
              sudo R -q -e "options(repos=c(CRAN=paste0('https://packagemanager.posit.co/cran/__linux__/', system('lsb_release -cs', intern=TRUE), '/latest')), HTTPUserAgent=sprintf('R/%s>
      - run:
          command: |
              sudo Rscript -e 'library(covr); covr::codecov(token = "'$CODECOV_TOKEN'")'
workflows:
  build:
    jobs:
      - dsbase
